org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

libVersion=1.0

# Type tracker pour la synchronisation de lecture
extType=tracker
extId=LiSync
extClass=AndroidED

extIconUrl=https://i.scdn.co/image/ab67616d0000b273c8383f905616ee873c80b8df
extName=LiSync
extDescription=Listening Sync Extension for Echo.

extAuthor=Vessel69
extAuthorUrl=

extRepoUrl=
extUpdateUrl=
